export const questions = [
  {
    id: 1,
    question: "This is __ ball.",
    answers: ["a", "the", "__", "an"],
    correctAnswer: "a",
    answeredCorrectly: false,
    difficulty: "easy level",
    isReset: false,
  },
  {
    id: 2,
    question: "You aren't hungry now, ___ you?",
    answers: ["are", "didn't", "will", "is"],
    correctAnswer: "are",
    answeredCorrectly: false,
    difficulty: "easy level",
    isReset: false,
  },
  {
    id: 3,
    question: "He __ a boy.",
    answers: ["has", "are", "will", "is"],
    correctAnswer: "is",
    answeredCorrectly: false,
    difficulty: "easy level",
    isReset: false,
  },
  {
    id: 4,
    question: "I buy meat at a __ .",
    answers: ["clothing shop", "butcher shop", "barbershop", "library"],
    correctAnswer: "butcher shop",
    answeredCorrectly: false,
    difficulty: "average level",
    isReset: false,
  },
  {
    id: 5,
    question: "I have never been __ London.",
    answers: ["into", "at", "to", "in"],
    correctAnswer: "to",
    answeredCorrectly: false,
    difficulty: "average level",
    isReset: false,
  },
  {
    id: 6,
    question: "I __ my mum.",
    answers: ["look", "am looking", "am", "look like"],
    correctAnswer: "look like",
    answeredCorrectly: false,
    difficulty: "average level",
    isReset: false,
  },
  {
    id: 7,
    question: "__ wallet is this? It's his.",
    answers: ["Who's", "Whose", "Who'se", "His"],
    correctAnswer: "Whose",
    answeredCorrectly: false,
    difficulty: "average level",
    isReset: false,
  },
  {
    id: 8,
    question: "The doctor __ me that there would be no pain.",
    answers: ["sured", "insured", "reassured", "ensured"],
    correctAnswer: "reassured",
    answeredCorrectly: false,
    difficulty: "advanced level",
    isReset: false,
  },
  {
    id: 9,
    question: "We try to be __ to the needs of the customer.",
    answers: ["responsible", "responsive", "respondent", "response"],
    correctAnswer: "responsive",
    answeredCorrectly: false,
    difficulty: "advanced level",
    isReset: false,
  },
  {
    id: 10,
    question: "This particular college has a very selective __ policy.",
    answers: ["entrance", "admissions", "admittance", "acceptance"],
    correctAnswer: "admissions",
    answeredCorrectly: false,
    difficulty: "advanced level",
    isReset: false,
  },
];
